export const CHILD_STATUS = {
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
};

export const PAGE_STATUS = {
  ENTERING_PARENT_NAME: 'ENTERING_PARENT_NAME',
  SELECT_CHILDREN: 'SELECT_CHILDREN',
  CHECKING_CHILD_IN: 'CHECKING_CHILD_IN',
  CHILDREN_CHECKED_IN: 'CHILDREN_CHECKED_IN',
  CHECKING_CHILD_OUT: 'CHECKING_CHILD_OUT',
  CHILDREN_CHECKED_OUT: 'CHILDREN_CHECKED_OUT',
};
